# Generated by Django 4.0.5 on 2022-07-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='subTitulo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='titulo',
            new_name='resumen',
        ),
    ]
