# Generated by Django 4.0.5 on 2022-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0005_vehiculo_categoria_vehiculo_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
    ]
